package org.cmcc.ecip.common.sms;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-07T14:03:33.531+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "ISmsWebServiceService", 
                  wsdlLocation = "smsService.wsdl",
                  targetNamespace = "http://www.sms.upbms.hp.com") 
public class ISmsWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.sms.upbms.hp.com", "ISmsWebServiceService");
    public final static QName ISmsWebServicePort = new QName("http://www.sms.upbms.hp.com", "ISmsWebServicePort");
    static {
        URL url = ISmsWebServiceService.class.getResource("smsService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ISmsWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "smsService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ISmsWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ISmsWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISmsWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ISmsWebService
     */
    @WebEndpoint(name = "ISmsWebServicePort")
    public ISmsWebService getISmsWebServicePort() {
        return super.getPort(ISmsWebServicePort, ISmsWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISmsWebService
     */
    @WebEndpoint(name = "ISmsWebServicePort")
    public ISmsWebService getISmsWebServicePort(WebServiceFeature... features) {
        return super.getPort(ISmsWebServicePort, ISmsWebService.class);
    }

}
