package org.cmcc.ecip.common.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-07T14:03:33.484+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://www.sms.upbms.hp.com", name = "ISmsWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ISmsWebService {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "smsService", targetNamespace = "http://www.sms.upbms.hp.com", className = "com.hp.ecip.bmc.core.smm.SmsService")
    @WebMethod
    @ResponseWrapper(localName = "smsServiceResponse", targetNamespace = "http://www.sms.upbms.hp.com", className = "com.hp.ecip.bmc.core.smm.SmsServiceResponse")
    public java.lang.String smsService(
        @WebParam(name = "target", targetNamespace = "")
        java.lang.String target,
        @WebParam(name = "action", targetNamespace = "")
        java.lang.String action,
        @WebParam(name = "xmldata", targetNamespace = "")
        java.lang.String xmldata,
        @WebParam(name = "brief", targetNamespace = "")
        java.lang.String brief
    );
}
